// nav-config.js
// Purpose: Defines the navigation structure and permissions for the ERP application's sidebar and menus.
// Used by the UI to render navigation, check access, and organize modules/screens by group and scope.
//
// Exports:
// - navConfig: Array of navigation groups, screens, and their metadata (route, label, scope, etc).
// - syncNavScopes: (if present) Utility to sync navigation scopes with permissions.

const navConfig = [
  {
    key: "administration",
    labelKey: "administration",
    scopeType: "MODULE",
    scopeKey: "administration",
    moduleGroup: "Administration",
    children: [
      {
        key: "setup",
        labelKey: "setup",
        type: "group",
        children: [
          {
            key: "branches",
            labelKey: "branches",
            scopeType: "SCREEN",
            scopeKey: "administration.branches",
            moduleGroup: "Administration",
            route: "/administration/branches",
          },
          {
            key: "users",
            labelKey: "users",
            scopeType: "SCREEN",
            scopeKey: "administration.users",
            moduleGroup: "Administration",
            route: "/administration/users",
          },
          {
            key: "roles",
            labelKey: "roles",
            scopeType: "SCREEN",
            scopeKey: "administration.roles",
            moduleGroup: "Administration",
            route: "/administration/roles",
          },
          {
            key: "permissions",
            labelKey: "permissions",
            scopeType: "SCREEN",
            scopeKey: "administration.permissions",
            moduleGroup: "Administration",
            route: "/administration/permissions",
          },
        ],
      },
      {
        key: "approvals",
        labelKey: "approvals",
        type: "group",
        children: [
          {
            key: "approvals",
            labelKey: "approvals",
            scopeType: "SCREEN",
            scopeKey: "administration.approvals",
            moduleGroup: "Administration",
            route: "/administration/approvals",
          },
          {
            key: "approval_settings",
            labelKey: "approval_settings",
            scopeType: "SCREEN",
            scopeKey: "administration.approval_settings",
            moduleGroup: "Administration",
            route: "/administration/approvals/settings",
          },
          {
            key: "audit_logs",
            labelKey: "audit_logs",
            scopeType: "SCREEN",
            scopeKey: "administration.audit_logs",
            moduleGroup: "Administration",
            route: "/administration/audit-logs",
          },
        ],
      },
    ],
  },
  {
    key: "master_data",
    labelKey: "master_data",
    scopeType: "MODULE",
    scopeKey: "master_data",
    moduleGroup: "Master Data",
    children: [
      {
        key: "basic_information",
        labelKey: "basic_information",
        type: "group",
        children: [
          {
            key: "units",
            labelKey: "units",
            scopeType: "SCREEN",
            scopeKey: "master_data.basic_info.units",
            moduleGroup: "Master Data",
            route: "/master-data/basic-info/units",
          },
          {
            key: "groups",
            labelKey: "groups",
            type: "group",
            children: [
              {
                key: "product_groups",
                labelKey: "product_groups",
                scopeType: "SCREEN",
                scopeKey: "master_data.basic_info.product_groups",
                moduleGroup: "Master Data",
                route: "/master-data/basic-info/product-groups",
              },
              {
                key: "product_subgroups",
                labelKey: "product_subgroups",
                scopeType: "SCREEN",
                scopeKey: "master_data.basic_info.product_subgroups",
                moduleGroup: "Master Data",
                route: "/master-data/basic-info/product-subgroups",
              },
              {
                key: "product_types",
                labelKey: "product_types",
                scopeType: "SCREEN",
                scopeKey: "master_data.basic_info.product_types",
                moduleGroup: "Master Data",
                route: "/master-data/basic-info/product-types",
              },
              {
                key: "party_groups",
                labelKey: "party_groups",
                scopeType: "SCREEN",
                scopeKey: "master_data.basic_info.party_groups",
                moduleGroup: "Master Data",
                route: "/master-data/basic-info/party-groups",
              },
              {
                key: "account_groups",
                labelKey: "account_groups",
                scopeType: "SCREEN",
                scopeKey: "master_data.basic_info.account_groups",
                moduleGroup: "Master Data",
                route: "/master-data/basic-info/account-groups",
              },
              {
                key: "departments",
                labelKey: "departments",
                scopeType: "SCREEN",
                scopeKey: "master_data.basic_info.departments",
                moduleGroup: "Master Data",
                route: "/master-data/basic-info/departments",
              },
              {
                key: "production_stages",
                labelKey: "production_stages",
                scopeType: "SCREEN",
                scopeKey: "master_data.basic_info.production_stages",
                moduleGroup: "Master Data",
                route: "/master-data/basic-info/production-stages",
              },
            ],
          },
          {
            key: "sizes",
            labelKey: "sizes",
            scopeType: "SCREEN",
            scopeKey: "master_data.basic_info.sizes",
            moduleGroup: "Master Data",
            route: "/master-data/basic-info/sizes",
          },
          {
            key: "colors",
            labelKey: "colors",
            scopeType: "SCREEN",
            scopeKey: "master_data.basic_info.colors",
            moduleGroup: "Master Data",
            route: "/master-data/basic-info/colors",
          },
          {
            key: "grades",
            labelKey: "grades",
            scopeType: "SCREEN",
            scopeKey: "master_data.basic_info.grades",
            moduleGroup: "Master Data",
            route: "/master-data/basic-info/grades",
          },
          {
            key: "packing_types",
            labelKey: "packing_types",
            scopeType: "SCREEN",
            scopeKey: "master_data.basic_info.packing_types",
            moduleGroup: "Master Data",
            route: "/master-data/basic-info/packing-types",
          },
          {
            key: "cities",
            labelKey: "cities",
            scopeType: "SCREEN",
            scopeKey: "master_data.basic_info.cities",
            moduleGroup: "Master Data",
            route: "/master-data/basic-info/cities",
          },
          {
            key: "uom_conversions",
            labelKey: "uom_conversions",
            scopeType: "SCREEN",
            scopeKey: "master_data.basic_info.uom_conversions",
            moduleGroup: "Master Data",
            route: "/master-data/basic-info/uom-conversions",
          },
        ],
      },
      {
        key: "accounts_parties",
        labelKey: "accounts_parties",
        type: "group",
        children: [
          {
            key: "accounts",
            labelKey: "accounts",
            scopeType: "SCREEN",
            scopeKey: "master_data.accounts",
            moduleGroup: "Master Data",
            route: "/master-data/accounts",
          },
          {
            key: "parties",
            labelKey: "parties",
            scopeType: "SCREEN",
            scopeKey: "master_data.parties",
            moduleGroup: "Master Data",
            route: "/master-data/parties",
          },
        ],
      },
      {
        key: "assets",
        labelKey: "assets",
        type: "group",
        children: [
          {
            key: "assets_master",
            labelKey: "asset_master",
            scopeType: "SCREEN",
            scopeKey: "master_data.returnable_assets",
            moduleGroup: "Master Data",
            route: "/master-data/assets",
          },
          {
            key: "asset_types",
            labelKey: "asset_types",
            scopeType: "SCREEN",
            scopeKey: "master_data.asset_types",
            moduleGroup: "Master Data",
            route: "/master-data/asset-types",
          },
        ],
      },
      {
        key: "products",
        labelKey: "products",
        type: "group",
        children: [
          {
            key: "finished",
            labelKey: "finished",
            scopeType: "SCREEN",
            scopeKey: "master_data.products.finished",
            moduleGroup: "Master Data",
            route: "/master-data/products/finished",
          },
          {
            key: "semi_finished",
            labelKey: "semi_finished",
            scopeType: "SCREEN",
            scopeKey: "master_data.products.semi_finished",
            moduleGroup: "Master Data",
            route: "/master-data/products/semi-finished",
          },
          {
            key: "raw_materials",
            labelKey: "raw_materials",
            scopeType: "SCREEN",
            scopeKey: "master_data.products.raw_materials",
            moduleGroup: "Master Data",
            route: "/master-data/products/raw-materials",
          },
          {
            key: "skus",
            labelKey: "skus",
            scopeType: "SCREEN",
            scopeKey: "master_data.products.skus",
            moduleGroup: "Master Data",
            route: "/master-data/products/skus",
          },
        ],
      },
      {
        key: "bom",
        labelKey: "bom",
        type: "group",
        children: [
          {
            key: "bom_list",
            labelKey: "bom_list",
            scopeType: "SCREEN",
            scopeKey: "master_data.bom",
            moduleGroup: "Master Data",
            route: "/master-data/bom",
          },
          {
            key: "bom_versions",
            labelKey: "bom_versions",
            scopeType: "SCREEN",
            scopeKey: "master_data.bom.versions",
            moduleGroup: "Master Data",
            route: "/master-data/bom/versions",
          },
        ],
      },
    ],
  },
  {
    key: "hr_payroll",
    labelKey: "hr_payroll",
    scopeType: "MODULE",
    scopeKey: "hr_payroll",
    moduleGroup: "HR & Payroll",
    children: [
      {
        key: "employees",
        labelKey: "employees",
        type: "group",
        children: [
          {
            key: "employees_list",
            labelKey: "employees",
            scopeType: "SCREEN",
            scopeKey: "hr_payroll.employees",
            moduleGroup: "HR & Payroll",
            route: "/hr-payroll/employees",
          },
          {
            key: "sales_commission",
            labelKey: "sales_commission",
            scopeType: "SCREEN",
            scopeKey: "hr_payroll.commissions",
            moduleGroup: "HR & Payroll",
            route: "/hr-payroll/employees/commissions",
          },
          {
            key: "allowances",
            labelKey: "allowances",
            scopeType: "SCREEN",
            scopeKey: "hr_payroll.allowances",
            moduleGroup: "HR & Payroll",
            route: "/hr-payroll/employees/allowances",
          },
        ],
      },
      {
        key: "labours",
        labelKey: "labours",
        type: "group",
        children: [
          {
            key: "labours_list",
            labelKey: "labours",
            scopeType: "SCREEN",
            scopeKey: "hr_payroll.labours",
            moduleGroup: "HR & Payroll",
            route: "/hr-payroll/labours",
          },
          {
            key: "labour_rates",
            labelKey: "labour_rates",
            scopeType: "SCREEN",
            scopeKey: "hr_payroll.labour_rates",
            moduleGroup: "HR & Payroll",
            route: "/hr-payroll/labours/rates",
          },
        ],
      },
    ],
  },
  {
    key: "financial",
    labelKey: "financial",
    scopeType: "MODULE",
    scopeKey: "financial",
    moduleGroup: "Financial",
    children: [
      {
        key: "vouchers",
        labelKey: "vouchers",
        type: "group",
        children: [
          {
            key: "cash_voucher",
            labelKey: "cash_voucher",
            scopeType: "VOUCHER",
            scopeKey: "CASH_VOUCHER",
            moduleGroup: "Financial",
            route: "/vouchers/cash",
          },
          {
            key: "bank_voucher",
            labelKey: "bank_voucher",
            scopeType: "VOUCHER",
            scopeKey: "BANK_VOUCHER",
            moduleGroup: "Financial",
            route: "/vouchers/bank",
          },
          {
            key: "journal_voucher",
            labelKey: "journal_voucher",
            scopeType: "VOUCHER",
            scopeKey: "JOURNAL_VOUCHER",
            moduleGroup: "Financial",
            route: "/vouchers/journal",
          },
        ],
      },
      {
        key: "reports",
        labelKey: "reports",
        type: "group",
        children: [
          {
            key: "cash_book",
            labelKey: "cash_book",
            scopeType: "REPORT",
            scopeKey: "cash_book",
            moduleGroup: "Financial",
            route: "/reports/financial/cash_book",
          },
          {
            key: "voucher_register",
            labelKey: "voucher_register",
            scopeType: "REPORT",
            scopeKey: "voucher_register",
            moduleGroup: "Financial",
            route: "/reports/financial/voucher_register",
          },
          {
            key: "expense_analysis",
            labelKey: "expense_analysis",
            scopeType: "REPORT",
            scopeKey: "expense_analysis",
            moduleGroup: "Financial",
            route: "/reports/financial/expense_analysis",
          },
          {
            key: "expense_trends",
            labelKey: "expense_trends",
            scopeType: "REPORT",
            scopeKey: "expense_trends",
            moduleGroup: "Financial",
            route: "/reports/financial/expense_trends",
          },
          {
            key: "profitability_analysis",
            labelKey: "profitability_analysis",
            scopeType: "REPORT",
            scopeKey: "profitability_analysis",
            moduleGroup: "Financial",
            route: "/reports/financial/profitability_analysis",
          },
          {
            key: "profit_and_loss",
            labelKey: "profit_and_loss",
            scopeType: "REPORT",
            scopeKey: "profit_and_loss",
            moduleGroup: "Financial",
            route: "/reports/financial/profit_and_loss",
          },
          {
            key: "account_activity_ledger",
            labelKey: "account_activity_ledger",
            scopeType: "REPORT",
            scopeKey: "account_activity_ledger",
            moduleGroup: "Financial",
            route: "/reports/financial/account_activity_ledger",
          },
          {
            key: "trial_balance",
            labelKey: "trial_balance",
            scopeType: "REPORT",
            scopeKey: "trial_balance",
            moduleGroup: "Financial",
            route: "/reports/financial/trial_balance",
          },
          {
            key: "payroll_wage_balance",
            labelKey: "payroll_wage_balance",
            scopeType: "REPORT",
            scopeKey: "payroll_wage_balance",
            moduleGroup: "Financial",
            route: "/reports/financial/payroll_wage_balance",
          },
        ],
      },
    ],
  },
  {
    key: "purchase",
    labelKey: "purchase",
    scopeType: "MODULE",
    scopeKey: "purchase",
    moduleGroup: "Purchase",
    children: [
      {
        key: "purchase",
        labelKey: "vouchers",
        type: "group",
        children: [
          {
            key: "goods_receipt_note",
            labelKey: "goods_receipt_note_voucher",
            scopeType: "VOUCHER",
            scopeKey: "GRN",
            moduleGroup: "Purchase",
            route: "/vouchers/goods-receipt-note",
          },
          {
            key: "general_purchase",
            labelKey: "general_purchase_voucher",
            scopeType: "VOUCHER",
            scopeKey: "PI",
            moduleGroup: "Purchase",
            route: "/vouchers/purchase",
          },
          {
            key: "purchase_return",
            labelKey: "purchase_return_voucher",
            scopeType: "VOUCHER",
            scopeKey: "PR",
            moduleGroup: "Purchase",
            route: "/vouchers/purchase-return",
          },
        ],
      },
      {
        key: "supplier_reports",
        labelKey: "supplier_reports",
        type: "group",
        children: [
          {
            key: "supplier_listings",
            labelKey: "supplier_listings",
            scopeType: "REPORT",
            scopeKey: "purchase_report",
            moduleGroup: "Purchase",
            route: "/reports/purchases/supplier-listings",
          },
          {
            key: "supplier_ledger_report",
            labelKey: "supplier_ledger_report",
            scopeType: "REPORT",
            scopeKey: "supplier_ledger",
            moduleGroup: "Purchase",
            route: "/reports/purchases/supplier-ledger",
          },
          {
            key: "supplier_balances_report",
            labelKey: "supplier_balances_report",
            scopeType: "REPORT",
            scopeKey: "supplier_balances",
            moduleGroup: "Purchase",
            route: "/reports/purchases/supplier-balances",
          },
        ],
      },
      {
        key: "reports",
        labelKey: "reports",
        type: "group",
        children: [
          {
            key: "purchase_reports",
            labelKey: "purchase_reports",
            scopeType: "REPORT",
            scopeKey: "purchase_report",
            moduleGroup: "Purchase",
            route: "/reports/purchases",
          },
        ],
      },
    ],
  },
  {
    key: "production",
    labelKey: "production",
    scopeType: "MODULE",
    scopeKey: "production",
    moduleGroup: "Production",
    children: [
      {
        key: "production",
        labelKey: "vouchers",
        type: "group",
        children: [
          {
            key: "department_completion_voucher",
            labelKey: "department_completion_voucher",
            scopeType: "VOUCHER",
            scopeKey: "DCV",
            moduleGroup: "Production",
            route: "/vouchers/department-completion",
          },
          {
            key: "consumption_voucher",
            labelKey: "consumption_voucher",
            scopeType: "VOUCHER",
            scopeKey: "CONSUMP",
            moduleGroup: "Production",
            route: "/vouchers/consumption",
          },
          {
            key: "labour_production_voucher",
            labelKey: "labour_production_voucher",
            scopeType: "VOUCHER",
            scopeKey: "LABOUR_PROD",
            moduleGroup: "Production",
            route: "/vouchers/labour-production",
          },
          {
            key: "production_planning_voucher",
            labelKey: "production_planning_voucher",
            scopeType: "VOUCHER",
            scopeKey: "PROD_PLAN",
            moduleGroup: "Production",
            route: "/vouchers/production-planning",
          },
          {
            key: "abnormal_loss",
            labelKey: "abnormal_loss_voucher",
            scopeType: "VOUCHER",
            scopeKey: "LOSS",
            moduleGroup: "Production",
            route: "/vouchers/abnormal-loss",
          },
        ],
      },
      {
        key: "reports",
        labelKey: "reports",
        type: "group",
        children: [
          {
            key: "production_reports",
            labelKey: "production_reports",
            scopeType: "REPORT",
            scopeKey: "production_report",
            moduleGroup: "Production",
            route: "/reports/production",
          },
        ],
      },
    ],
  },
  {
    key: "inventory",
    labelKey: "inventory",
    scopeType: "MODULE",
    scopeKey: "inventory",
    moduleGroup: "Inventory",
    children: [
      {
        key: "inventory",
        labelKey: "inventory",
        type: "group",
        children: [
          {
            key: "inventory_voucher",
            labelKey: "inventory_voucher",
            scopeType: "VOUCHER",
            scopeKey: "OPENING_STOCK",
            moduleGroup: "Inventory",
            route: "/vouchers/inventory",
          },
          {
            key: "stock_count",
            labelKey: "stock_count",
            scopeType: "VOUCHER",
            scopeKey: "STOCK_COUNT_ADJ",
            moduleGroup: "Inventory",
            route: "/vouchers/stock-count",
          },
          {
            key: "stock_transfer",
            labelKey: "stock_transfer",
            scopeType: "VOUCHER",
            scopeKey: "STN_OUT",
            moduleGroup: "Inventory",
            route: "/vouchers/stn",
          },
        ],
      },
      {
        key: "reports",
        labelKey: "reports",
        type: "group",
        children: [
          {
            key: "inventory_reports",
            labelKey: "inventory_reports",
            scopeType: "REPORT",
            scopeKey: "stock_quantity",
            moduleGroup: "Inventory",
            route: "/reports/inventory",
          },
        ],
      },
    ],
  },
  {
    key: "outward_returnable",
    labelKey: "outward_returnable",
    scopeType: "MODULE",
    scopeKey: "outward_returnable",
    moduleGroup: "Outward & Returnable",
    children: [
      {
        key: "vouchers",
        labelKey: "vouchers",
        type: "group",
        children: [
          {
            key: "returnable_dispatch_voucher",
            labelKey: "returnable_dispatch_voucher",
            scopeType: "VOUCHER",
            scopeKey: "RDV",
            moduleGroup: "Outward & Returnable",
            route: "/vouchers/returnable-dispatch",
          },
          {
            key: "returnable_receipt_voucher",
            labelKey: "returnable_receipt_voucher",
            scopeType: "VOUCHER",
            scopeKey: "RRV",
            moduleGroup: "Outward & Returnable",
            route: "/vouchers/returnable-receipt",
          },
        ],
      },
      {
        key: "reports",
        labelKey: "reports",
        type: "group",
        children: [
          {
            key: "pending_returnables_report",
            labelKey: "pending_returnables",
            scopeType: "REPORT",
            scopeKey: "pending_returnables",
            moduleGroup: "Outward & Returnable",
            route: "/reports/returnables/control",
          },
          {
            key: "overdue_returnables_report",
            labelKey: "overdue_returnables",
            scopeType: "REPORT",
            scopeKey: "pending_returnables",
            moduleGroup: "Outward & Returnable",
            route: "/reports/returnables/vendor-performance",
          },
        ],
      },
    ],
  },
  {
    key: "sales",
    labelKey: "sales",
    scopeType: "MODULE",
    scopeKey: "sales",
    moduleGroup: "Sales",
    children: [
      {
        key: "sales",
        labelKey: "sales",
        type: "group",
        children: [
          {
            key: "sales_voucher",
            labelKey: "sales_voucher",
            scopeType: "VOUCHER",
            scopeKey: "SALES_VOUCHER",
            moduleGroup: "Sales",
            route: "/vouchers/sales",
          },
          {
            key: "sales_order",
            labelKey: "sales_order",
            scopeType: "VOUCHER",
            scopeKey: "SALES_ORDER",
            moduleGroup: "Sales",
            route: "/vouchers/sales-order",
          },
          {
            key: "sales_discount_policies",
            labelKey: "sales_discount_policies",
            scopeType: "SCREEN",
            scopeKey: "master_data.basic_info.sales_discount_policies",
            moduleGroup: "Sales",
            route: "/master-data/basic-info/sales-discount-policies",
          },
        ],
      },
      {
        key: "customer_reports",
        labelKey: "customer_reports",
        type: "group",
        children: [
          {
            key: "customer_balances_report",
            labelKey: "customer_balances_report",
            scopeType: "REPORT",
            scopeKey: "sales_report",
            moduleGroup: "Sales",
            route: "/reports/sales/customer-balances",
          },
          {
            key: "customer_ledger_report",
            labelKey: "customer_ledger_report",
            scopeType: "REPORT",
            scopeKey: "sales_report",
            moduleGroup: "Sales",
            route: "/reports/sales/customer-ledger",
          },
          {
            key: "customer_listings",
            labelKey: "customer_listings",
            scopeType: "REPORT",
            scopeKey: "sales_report",
            moduleGroup: "Sales",
            route: "/reports/sales/customer-listings",
          },
          {
            key: "customer_contact_analysis",
            labelKey: "customer_contact_analysis",
            scopeType: "REPORT",
            scopeKey: "sales_report",
            moduleGroup: "Sales",
            route: "/reports/sales/customer-contact-analysis",
          },
        ],
      },
      {
        key: "sales_reports",
        labelKey: "sales_reports",
        type: "group",
        children: [
          {
            key: "sales_order_report",
            labelKey: "sales_order_report",
            scopeType: "REPORT",
            scopeKey: "sales_report",
            moduleGroup: "Sales",
            route: "/reports/sales/sales-order-report",
          },
          {
            key: "sales_report",
            labelKey: "sales_report",
            scopeType: "REPORT",
            scopeKey: "sales_report",
            moduleGroup: "Sales",
            route: "/reports/sales/sales-report",
          },
          {
            key: "sale_return_report",
            labelKey: "sale_return_report",
            scopeType: "REPORT",
            scopeKey: "sales_report",
            moduleGroup: "Sales",
            route: "/reports/sales/sale-return-report",
          },
          {
            key: "sales_discount_report",
            labelKey: "sales_discount_report",
            scopeType: "REPORT",
            scopeKey: "sales_report",
            moduleGroup: "Sales",
            route: "/reports/sales/sales-discount-report",
          },
        ],
      },
    ],
  },
];

const collectNavItems = (nodes, items = []) => {
  nodes.forEach((node) => {
    if (node.scopeType && node.scopeKey) {
      items.push({
        scopeType: node.scopeType,
        scopeKey: node.scopeKey,
        description: node.labelKey,
        moduleGroup: node.moduleGroup || null,
      });
    }
    if (node.children && node.children.length) {
      collectNavItems(node.children, items);
    }
  });
  return items;
};

const getNavScopes = () => collectNavItems(navConfig);

const syncNavScopes = async (knex) => {
  const scopes = getNavScopes();
  if (!scopes.length) return;
  const insertRows = scopes.map((scope) => ({
    scope_type: scope.scopeType,
    scope_key: scope.scopeKey,
    description: scope.description,
    module_group: scope.moduleGroup,
  }));

  await knex("erp.permission_scope_registry")
    .insert(insertRows)
    .onConflict(["scope_type", "scope_key"])
    .ignore();
};

module.exports = {
  navConfig,
  getNavScopes,
  syncNavScopes,
};
