-- =============================================================================
-- 030_voucher_engine.sql
-- =============================================================================
-- Goal:
--   One common voucher engine used by all modules (Sales, Purchase, Production, etc.)
--   so numbering, approvals, audit, and posting logic stays consistent.
--
-- Tables:
--   voucher_type   = defines each voucher template (SV, PV, JV, etc.)
--   voucher_header = one row per voucher document
--   voucher_line   = one row per voucher line (grid row)
-- =============================================================================

SET search_path = erp;

-- -----------------------------------------------------------------------------
-- voucher_type
-- -----------------------------------------------------------------------------
-- Master list of voucher types supported by the ERP.
-- Flags tell the app how to treat each voucher type:
--   requires_approval = should it go through maker-checker?
--   affects_stock     = should it create inventory movement/valuation?
--   affects_gl        = should it create GL postings when approved?
CREATE TABLE IF NOT EXISTS erp.voucher_type (
  code              text PRIMARY KEY, -- short stable key: SV, PV, JV, etc.
  name              text NOT NULL,    -- display name shown in UI
  requires_approval boolean NOT NULL DEFAULT false,
  affects_stock     boolean NOT NULL DEFAULT false,
  affects_gl        boolean NOT NULL DEFAULT true
);

-- -----------------------------------------------------------------------------
-- voucher_header
-- -----------------------------------------------------------------------------
-- One row per voucher document (top portion of voucher form).
-- voucher_no is the document number visible to the user (generated by app per branch/type).
CREATE TABLE IF NOT EXISTS erp.voucher_header (
  id                bigserial PRIMARY KEY,

  voucher_type_code text NOT NULL
                    REFERENCES erp.voucher_type(code)
                    ON DELETE RESTRICT,

  voucher_no         bigint NOT NULL, -- app-generated
  branch_id          bigint NOT NULL REFERENCES erp.branches(id) ON DELETE RESTRICT,
  voucher_date       date NOT NULL,
  book_no            text,

  -- Approval status for maker-checker stage.
  -- If you later introduce posting as a separate finalization step,
  status             erp.approval_status NOT NULL DEFAULT 'PENDING',

  created_by         bigint NOT NULL REFERENCES erp.users(id) ON DELETE RESTRICT,
  created_at         timestamptz NOT NULL DEFAULT now(),

  approved_by        bigint REFERENCES erp.users(id) ON DELETE RESTRICT,
  approved_at        timestamptz,

  remarks            text,

  -- Consistency:
  -- - While PENDING: no approval fields
  -- - Once APPROVED/REJECTED: approver + timestamp must exist
  CHECK (
    (status = 'PENDING' AND approved_by IS NULL AND approved_at IS NULL)
    OR
    (status IN ('APPROVED','REJECTED') AND approved_by IS NOT NULL AND approved_at IS NOT NULL)
  ),

  -- Unique numbering series per branch per voucher type
  UNIQUE (branch_id, voucher_type_code, voucher_no)
);

-- -----------------------------------------------------------------------------
-- voucher_line
-- -----------------------------------------------------------------------------
-- Each voucher has multiple lines (grid rows).
-- Exactly ONE reference must be set based on line_kind:
--   ITEM, SKU, ACCOUNT, PARTY, LABOUR, EMPLOYEE
CREATE TABLE IF NOT EXISTS erp.voucher_line (
  id                bigserial PRIMARY KEY,

  voucher_header_id bigint NOT NULL
                    REFERENCES erp.voucher_header(id)
                    ON DELETE CASCADE,

  line_no           int NOT NULL,
  line_kind         erp.voucher_line_kind NOT NULL,

  item_id           bigint REFERENCES erp.items(id)     ON DELETE RESTRICT,
  sku_id            bigint REFERENCES erp.skus(id)      ON DELETE RESTRICT,
  account_id        bigint REFERENCES erp.accounts(id)  ON DELETE RESTRICT,
  party_id          bigint REFERENCES erp.parties(id)   ON DELETE RESTRICT,
  labour_id         bigint REFERENCES erp.labours(id)   ON DELETE RESTRICT,
  employee_id       bigint REFERENCES erp.employees(id) ON DELETE RESTRICT,

  uom_id            bigint REFERENCES erp.uom(id)       ON DELETE RESTRICT,

  qty               numeric(18,3) NOT NULL DEFAULT 0,
  rate              numeric(18,4) NOT NULL DEFAULT 0,
  amount            numeric(18,2) NOT NULL DEFAULT 0,

  -- Extra per-line metadata (batch, narration, etc.)
  meta              jsonb NOT NULL DEFAULT '{}'::jsonb,

  UNIQUE (voucher_header_id, line_no),
  CHECK (line_no > 0),

  -- Ensure exactly one reference is filled
  CHECK (num_nonnulls(item_id, sku_id, account_id, party_id, labour_id, employee_id) = 1),

  -- Ensure the filled reference matches line_kind
  CHECK (
    (line_kind = 'ITEM'     AND item_id     IS NOT NULL) OR
    (line_kind = 'SKU'      AND sku_id      IS NOT NULL) OR
    (line_kind = 'ACCOUNT'  AND account_id  IS NOT NULL) OR
    (line_kind = 'PARTY'    AND party_id    IS NOT NULL) OR
    (line_kind = 'LABOUR'   AND labour_id   IS NOT NULL) OR
    (line_kind = 'EMPLOYEE' AND employee_id IS NOT NULL)
  )
);

-- Helpful index for fetching voucher lines quickly
CREATE INDEX IF NOT EXISTS idx_voucher_line_header
ON erp.voucher_line (voucher_header_id);
